version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  redis:
    image: redis:7.2-alpine
  keycloak:
    build: ./keycloak
    ports:
      - "8080:8080"
    environment:
      PROXY_ADDRESS_FORWARDING: "true"